all:
  ## コンパイルエンジン ##
  compile_engine:
    # Traditional Markdown (http://daringfireball.net/projects/markdown/syntax)
    - "Markdown"
    # GithubMarkdown (https://guides.github.com/features/mastering-markdown/)
    - "GithubMarkdown"
    # MarkdownExtra (https://michelf.ca/projects/php-markdown/extra/)
    - "MarkdownExtra"

  ## nteger the maximum nesting level for language elements. ##
  maximumNestingLevel: 32


  ## キャッシュの有無: enable caching
  is_compile_cache: true

  ## 必ずコンパイルするかどうか:always compiled
  is_force_compile: false

  ## ファイルが新しければキャッシュを作り直す
  use_intelligence_compile: true

  ## compile_idに自動付加するLessファイルのバージョン番号(これを更新すると、再コンパイルされます)
  ## The version number of the Less files to be automatically added to compile_id (If you update it, it will be recompiled)
  file_version: "1.0"

  ## キャッシュの保存先
  cache_path: "<?php echo ENVI_MVC_CACHE_PATH;?>"

  ## Markdown Extra拡張記法を使用する
  use_extra: true
dev:
  ## キャッシュの有無
  is_compile_cache: true
  ## 必ずコンパイルするかどうか
  is_force_compile: true

