
  CebeMarkdown:
  ################################
  # extension()->CebeMarkdown()の設定
  ################################
    ## ここをtrueにすると、リクエストごとにロードされ、オブジェクトが生成されます
    constant: false
    class:
      ## ファイルの実態
      resource: "<?php echo ENVI_BASE_DIR.'..'.DIRECTORY_SEPARATOR.'extensions'.DIRECTORY_SEPARATOR.'markdown'.DIRECTORY_SEPARATOR;?>EnviCebeMarkdownExtension.php"
      ## クラス名
      class_name: "EnviCebeMarkdownExtension"
      ## シングルトン化するか
      singleton: true
    router:
      ## extensionの設定のパス
      resource: "<?php echo dirname(__FILE__).DIRECTORY_SEPARATOR.$app_name.'_cebe_markdown.yml';?>"
